### PR TITLE
LPS-52584

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Applying same fix as we did in portal to web form: https://github.com/sergiogonzalez/liferay-portal/pull/1917

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-plugins/pull/259. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @hhuijser, Web Form belongs to Marcellus' Team now, thanks! :)

**Pull request closed without merging**
